CREATE TABLE clients (
    client_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name           VARCHAR2(255 CHAR) NOT NULL,
    phone               VARCHAR2(30 CHAR) NOT NULL,
    email               VARCHAR2(255 CHAR),
    registration_date   DATE DEFAULT SYSDATE NOT NULL,
    status              VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_clients PRIMARY KEY (client_id),
    CONSTRAINT uq_clients_phone UNIQUE (phone),
    CONSTRAINT uq_clients_email UNIQUE (email),
    CONSTRAINT chk_clients_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'ARCHIVED'))
);

COMMENT ON TABLE clients IS 'Клиенты сервиса аренды велосипедов';
COMMENT ON COLUMN clients.status IS 'ACTIVE, BLOCKED или ARCHIVED';


CREATE TABLE staff (
    staff_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name       VARCHAR2(255 CHAR) NOT NULL,
    job_title       VARCHAR2(100 CHAR) NOT NULL,
    login_name      VARCHAR2(100 CHAR),
    status          VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_staff PRIMARY KEY (staff_id),
    CONSTRAINT uq_staff_login UNIQUE (login_name),
    CONSTRAINT chk_staff_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'DISMISSED'))
);

COMMENT ON TABLE staff IS 'Сотрудники и администраторы сервиса';


CREATE TABLE rental_stations (
    station_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    station_name    VARCHAR2(150 CHAR) NOT NULL,
    address         VARCHAR2(300 CHAR) NOT NULL,
    phone           VARCHAR2(30 CHAR),
    status          VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_rental_stations PRIMARY KEY (station_id),
    CONSTRAINT uq_rental_stations_name UNIQUE (station_name),
    CONSTRAINT chk_rental_stations_status
        CHECK (status IN ('ACTIVE', 'TEMPORARILY_CLOSED', 'CLOSED'))
);

COMMENT ON TABLE rental_stations IS 'Пункты выдачи и возврата велосипедов';


CREATE TABLE bicycle_models (
    model_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    manufacturer        VARCHAR2(100 CHAR) NOT NULL,
    model_name          VARCHAR2(100 CHAR) NOT NULL,
    bicycle_type        VARCHAR2(30 CHAR) NOT NULL,
    default_hour_rate   NUMBER(10, 2) NOT NULL,
    description         VARCHAR2(1000 CHAR),

    CONSTRAINT pk_bicycle_models PRIMARY KEY (model_id),
    CONSTRAINT uq_bicycle_models UNIQUE (manufacturer, model_name),
    CONSTRAINT chk_bicycle_models_type
        CHECK (bicycle_type IN ('CITY', 'MOUNTAIN', 'ROAD', 'ELECTRIC')),
    CONSTRAINT chk_bicycle_models_rate
        CHECK (default_hour_rate > 0)
);

COMMENT ON TABLE bicycle_models IS 'Справочник моделей велосипедов';


CREATE TABLE bicycles (
    bicycle_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    inventory_number    VARCHAR2(50 CHAR) NOT NULL,
    model_id            NUMBER NOT NULL,
    station_id          NUMBER,
    status              VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    custom_hour_rate    NUMBER(10, 2),
    purchase_date       DATE,
    last_service_date   DATE,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bicycles PRIMARY KEY (bicycle_id),
    CONSTRAINT uq_bicycles_inventory UNIQUE (inventory_number),

    CONSTRAINT fk_bicycles_model
        FOREIGN KEY (model_id)
        REFERENCES bicycle_models(model_id),

    CONSTRAINT fk_bicycles_station
        FOREIGN KEY (station_id)
        REFERENCES rental_stations(station_id),

    CONSTRAINT chk_bicycles_status
        CHECK (status IN (
            'AVAILABLE',
            'RESERVED',
            'RENTED',
            'REPAIR',
            'BLOCKED',
            'RETIRED'
        )),

    CONSTRAINT chk_bicycles_rate
        CHECK (custom_hour_rate IS NULL OR custom_hour_rate > 0)
);

COMMENT ON TABLE bicycles IS 'Физические велосипеды проката';
COMMENT ON COLUMN bicycles.station_id IS 'Текущий пункт нахождения велосипеда';


CREATE TABLE bookings (
    booking_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id            NUMBER NOT NULL,
    bicycle_id           NUMBER NOT NULL,
    planned_start_at     TIMESTAMP NOT NULL,
    planned_end_at       TIMESTAMP NOT NULL,
    hold_until           TIMESTAMP,
    status               VARCHAR2(20 CHAR) DEFAULT 'NEW' NOT NULL,
    estimated_amount     NUMBER(10, 2),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    confirmed_at         TIMESTAMP,
    cancelled_at         TIMESTAMP,
    cancellation_reason  VARCHAR2(500 CHAR),

    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),

    CONSTRAINT fk_bookings_client
        FOREIGN KEY (client_id)
        REFERENCES clients(client_id),

    CONSTRAINT fk_bookings_bicycle
        FOREIGN KEY (bicycle_id)
        REFERENCES bicycles(bicycle_id),

    CONSTRAINT chk_bookings_period
        CHECK (planned_end_at > planned_start_at),

    CONSTRAINT chk_bookings_hold
        CHECK (hold_until IS NULL OR hold_until >= created_at),

    CONSTRAINT chk_bookings_status
        CHECK (status IN (
            'NEW',
            'CONFIRMED',
            'CANCELLED',
            'EXPIRED',
            'COMPLETED'
        )),

    CONSTRAINT chk_bookings_amount
        CHECK (estimated_amount IS NULL OR estimated_amount >= 0)
);

COMMENT ON TABLE bookings IS 'Предварительные бронирования велосипедов';


CREATE TABLE rentals (
    rental_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    booking_id          NUMBER,
    client_id           NUMBER NOT NULL,
    bicycle_id          NUMBER NOT NULL,
    start_station_id    NUMBER NOT NULL,
    end_station_id      NUMBER,
    planned_end_at      TIMESTAMP NOT NULL,
    actual_start_at     TIMESTAMP NOT NULL,
    actual_end_at       TIMESTAMP,
    status              VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    base_amount         NUMBER(10, 2) DEFAULT 0 NOT NULL,
    extension_amount    NUMBER(10, 2) DEFAULT 0 NOT NULL,
    penalty_amount      NUMBER(10, 2) DEFAULT 0 NOT NULL,
    total_amount        NUMBER(10, 2) DEFAULT 0 NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_rentals PRIMARY KEY (rental_id),
    CONSTRAINT uq_rentals_booking UNIQUE (booking_id),

    CONSTRAINT fk_rentals_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),

    CONSTRAINT fk_rentals_client
        FOREIGN KEY (client_id)
        REFERENCES clients(client_id),

    CONSTRAINT fk_rentals_bicycle
        FOREIGN KEY (bicycle_id)
        REFERENCES bicycles(bicycle_id),

    CONSTRAINT fk_rentals_start_station
        FOREIGN KEY (start_station_id)
        REFERENCES rental_stations(station_id),

    CONSTRAINT fk_rentals_end_station
        FOREIGN KEY (end_station_id)
        REFERENCES rental_stations(station_id),

    CONSTRAINT chk_rentals_status
        CHECK (status IN ('ACTIVE', 'OVERDUE', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT chk_rentals_planned_end
        CHECK (planned_end_at > actual_start_at),

    CONSTRAINT chk_rentals_actual_dates
        CHECK (actual_end_at IS NULL OR actual_end_at >= actual_start_at),

    CONSTRAINT chk_rentals_amounts
        CHECK (
            base_amount >= 0
            AND extension_amount >= 0
            AND penalty_amount >= 0
            AND total_amount >= 0
        )
);

COMMENT ON TABLE rentals IS 'Фактически начатые аренды';


CREATE TABLE rental_extensions (
    extension_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rental_id       NUMBER NOT NULL,
    old_end_at      TIMESTAMP NOT NULL,
    new_end_at      TIMESTAMP NOT NULL,
    amount          NUMBER(10, 2) NOT NULL,
    status          VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_rental_extensions PRIMARY KEY (extension_id),

    CONSTRAINT fk_rental_extensions_rental
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id),

    CONSTRAINT chk_rental_extensions_period
        CHECK (new_end_at > old_end_at),

    CONSTRAINT chk_rental_extensions_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_rental_extensions_status
        CHECK (status IN ('CREATED', 'PAID', 'CANCELLED'))
);

COMMENT ON TABLE rental_extensions IS 'История продлений аренды';


CREATE TABLE payments (
    payment_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rental_id           NUMBER,
    booking_id          NUMBER,
    client_id           NUMBER NOT NULL,
    payment_type        VARCHAR2(20 CHAR) NOT NULL,
    status              VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    amount              NUMBER(10, 2) NOT NULL,
    currency_code       VARCHAR2(3 CHAR) DEFAULT 'RUB' NOT NULL,
    payment_method      VARCHAR2(30 CHAR),
    external_payment_id VARCHAR2(100 CHAR),
    idempotency_key     VARCHAR2(100 CHAR),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    paid_at             TIMESTAMP,
    failed_at           TIMESTAMP,
    failure_reason      VARCHAR2(500 CHAR),

    CONSTRAINT pk_payments PRIMARY KEY (payment_id),

    CONSTRAINT fk_payments_rental
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id),

    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),

    CONSTRAINT fk_payments_client
        FOREIGN KEY (client_id)
        REFERENCES clients(client_id),

    CONSTRAINT uq_payments_external UNIQUE (external_payment_id),
    CONSTRAINT uq_payments_idempotency UNIQUE (idempotency_key),

    CONSTRAINT chk_payments_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payments_currency
        CHECK (currency_code IN ('RUB')),

    CONSTRAINT chk_payments_type
        CHECK (payment_type IN (
            'BOOKING',
            'RENTAL',
            'EXTENSION',
            'PENALTY',
            'REFUND'
        )),

    CONSTRAINT chk_payments_status
        CHECK (status IN (
            'CREATED',
            'PENDING',
            'SUCCESS',
            'FAILED',
            'REFUNDED'
        )),

    CONSTRAINT chk_payments_parent
        CHECK (rental_id IS NOT NULL OR booking_id IS NOT NULL),

    CONSTRAINT chk_payments_dates
        CHECK (
            (paid_at IS NULL OR paid_at >= created_at)
            AND (failed_at IS NULL OR failed_at >= created_at)
        )
);

COMMENT ON TABLE payments IS 'Платежи по бронированиям, арендам, продлениям и штрафам';


CREATE TABLE repair_orders (
    repair_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id           NUMBER NOT NULL,
    opened_by_staff_id   NUMBER NOT NULL,
    closed_by_staff_id   NUMBER,
    status               VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    problem_description  VARCHAR2(1000 CHAR) NOT NULL,
    repair_result        VARCHAR2(1000 CHAR),
    repair_cost          NUMBER(10, 2) DEFAULT 0 NOT NULL,
    opened_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    started_at           TIMESTAMP,
    completed_at         TIMESTAMP,

    CONSTRAINT pk_repair_orders PRIMARY KEY (repair_id),

    CONSTRAINT fk_repair_orders_bicycle
        FOREIGN KEY (bicycle_id)
        REFERENCES bicycles(bicycle_id),

    CONSTRAINT fk_repair_orders_opened_staff
        FOREIGN KEY (opened_by_staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT fk_repair_orders_closed_staff
        FOREIGN KEY (closed_by_staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT chk_repair_orders_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT chk_repair_orders_cost
        CHECK (repair_cost >= 0),

    CONSTRAINT chk_repair_orders_dates
        CHECK (
            (started_at IS NULL OR started_at >= opened_at)
            AND (completed_at IS NULL OR completed_at >= opened_at)
        )
);

COMMENT ON TABLE repair_orders IS 'Заявки на ремонт и техническое обслуживание';


CREATE TABLE bicycle_status_history (
    history_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id           NUMBER NOT NULL,
    old_status           VARCHAR2(20 CHAR),
    new_status           VARCHAR2(20 CHAR) NOT NULL,
    change_reason        VARCHAR2(500 CHAR),
    changed_by_staff_id  NUMBER,
    changed_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    source_type          VARCHAR2(30 CHAR),
    source_id            NUMBER,

    CONSTRAINT pk_bicycle_status_history PRIMARY KEY (history_id),

    CONSTRAINT fk_bicycle_history_bicycle
        FOREIGN KEY (bicycle_id)
        REFERENCES bicycles(bicycle_id),

    CONSTRAINT fk_bicycle_history_staff
        FOREIGN KEY (changed_by_staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT chk_bicycle_history_old_status
        CHECK (
            old_status IS NULL OR old_status IN (
                'AVAILABLE',
                'RESERVED',
                'RENTED',
                'REPAIR',
                'BLOCKED',
                'RETIRED'
            )
        ),

    CONSTRAINT chk_bicycle_history_new_status
        CHECK (
            new_status IN (
                'AVAILABLE',
                'RESERVED',
                'RENTED',
                'REPAIR',
                'BLOCKED',
                'RETIRED'
            )
        ),

    CONSTRAINT chk_bicycle_history_source
        CHECK (
            source_type IS NULL OR source_type IN (
                'BOOKING',
                'RENTAL',
                'REPAIR',
                'MANUAL',
                'SYSTEM'
            )
        )
);

COMMENT ON TABLE bicycle_status_history IS 'Бизнес-история смены статусов велосипедов';


CREATE TABLE audit_log (
    audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    audit_type      VARCHAR2(50 CHAR) NOT NULL,
    event_time      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    action_code     VARCHAR2(50 CHAR) NOT NULL,
    entity_name     VARCHAR2(50 CHAR) NOT NULL,
    entity_id       NUMBER,
    old_data        VARCHAR2(100 CHAR),
    new_data        VARCHAR2(100 CHAR),
    error_code      NUMBER,
    error_message   VARCHAR2(1000 CHAR),

    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),

        
    CONSTRAINT chk_audit_log_audit_type 
         CHECK (audit_type IN ('EVENT','ERROR'))
)
PARTITION BY RANGE (event_time)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
SUBPARTITION BY LIST (audit_type)
SUBPARTITION TEMPLATE
(
    SUBPARTITION sp_event VALUES ('EVENT'),
    SUBPARTITION sp_error VALUES ('ERROR'),
    SUBPARTITION sp_other VALUES (DEFAULT)
)
(
    PARTITION p_before_2026
        VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00')
);

COMMENT ON TABLE audit_log IS 'Общий технический аудит действий и изменений';

CREATE INDEX ix_bicycles_station_status
    ON bicycles (station_id, status);

CREATE INDEX ix_bookings_bicycle_period
    ON bookings (bicycle_id, status, planned_start_at, planned_end_at);

CREATE INDEX ix_bookings_client_created
    ON bookings (client_id, created_at);

CREATE INDEX ix_rentals_bicycle_status
    ON rentals (bicycle_id, status);

CREATE INDEX ix_rentals_client_start
    ON rentals (client_id, actual_start_at);

CREATE INDEX ix_rentals_start_station
    ON rentals (start_station_id);

CREATE INDEX ix_rentals_end_station
    ON rentals (end_station_id);

CREATE INDEX ix_payments_rental_status
    ON payments (rental_id, status);

CREATE INDEX ix_payments_booking_status
    ON payments (booking_id, status);

CREATE INDEX ix_repair_orders_bicycle_status
    ON repair_orders (bicycle_id, status);

CREATE INDEX ix_bicycle_history_bicycle_date
    ON bicycle_status_history (bicycle_id, changed_at);

CREATE INDEX ix_audit_log_entity
    ON audit_log (entity_name, entity_id, event_time);

CREATE INDEX ix_audit_log_event_time
    ON audit_log (event_time);



