CREATE TABLE dim_date (
    date_key            NUMBER(8) NOT NULL,
    full_date           DATE NOT NULL,

    day_number          NUMBER(2) NOT NULL,
    day_of_week_number  NUMBER(1) NOT NULL,
    day_name            VARCHAR2(20 CHAR) NOT NULL,

    week_number         NUMBER(2) NOT NULL,

    month_number        NUMBER(2) NOT NULL,
    month_name          VARCHAR2(20 CHAR) NOT NULL,

    quarter_number      NUMBER(1) NOT NULL,
    year_number         NUMBER(4) NOT NULL,

    is_weekend          CHAR(1) DEFAULT 'N' NOT NULL,

    CONSTRAINT pk_dim_date
        PRIMARY KEY (date_key),

    CONSTRAINT uq_dim_date
        UNIQUE (full_date),

    CONSTRAINT chk_dim_date_weekend
        CHECK (is_weekend IN ('Y', 'N')),

    CONSTRAINT chk_dim_date_day
        CHECK (day_number BETWEEN 1 AND 31),

    CONSTRAINT chk_dim_date_weekday
        CHECK (day_of_week_number BETWEEN 1 AND 7),

    CONSTRAINT chk_dim_date_month
        CHECK (month_number BETWEEN 1 AND 12),

    CONSTRAINT chk_dim_date_quarter
        CHECK (quarter_number BETWEEN 1 AND 4)
);

COMMENT ON TABLE dim_date IS
    'Календарное измерение DWH';

COMMENT ON COLUMN dim_date.date_key IS
    'Ключ даты в формате YYYYMMDD';
	CREATE TABLE dim_client (
    client_key          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id           NUMBER NOT NULL,

    full_name           VARCHAR2(255 CHAR) NOT NULL,
    email               VARCHAR2(255 CHAR),
    client_status       VARCHAR2(20 CHAR) NOT NULL,
    registration_date   DATE,

    valid_from          TIMESTAMP NOT NULL,
    valid_to            TIMESTAMP,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL,

    source_updated_at   TIMESTAMP,
    load_dttm           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dim_client
        PRIMARY KEY (client_key),

    CONSTRAINT chk_dim_client_current
        CHECK (is_current IN ('Y', 'N')),

    CONSTRAINT chk_dim_client_period
        CHECK (
            valid_to IS NULL
            OR valid_to > valid_from
        )
);

COMMENT ON TABLE dim_client IS
    'Измерение клиентов, SCD Type 2';

COMMENT ON COLUMN dim_client.client_key IS
    'Суррогатный ключ DWH';

COMMENT ON COLUMN dim_client.client_id IS
    'Бизнес-ключ клиента из OLTP';

COMMENT ON COLUMN dim_client.valid_from IS
    'Начало действия версии';

COMMENT ON COLUMN dim_client.valid_to IS
    'Окончание действия версии';

COMMENT ON COLUMN dim_client.is_current IS
    'Признак текущей версии записи';
	
CREATE TABLE dim_station (
    station_key         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    station_id          NUMBER NOT NULL,

    station_name        VARCHAR2(150 CHAR) NOT NULL,
    address             VARCHAR2(300 CHAR),
    phone               VARCHAR2(30 CHAR),
    station_status      VARCHAR2(20 CHAR),

    valid_from          TIMESTAMP NOT NULL,
    valid_to            TIMESTAMP,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL,

    source_updated_at   TIMESTAMP,
    load_dttm           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dim_station
        PRIMARY KEY (station_key),

    CONSTRAINT chk_dim_station_current
        CHECK (is_current IN ('Y', 'N')),

    CONSTRAINT chk_dim_station_period
        CHECK (
            valid_to IS NULL
            OR valid_to > valid_from
        )
);

COMMENT ON TABLE dim_station IS
    'Измерение пунктов выдачи и возврата, SCD Type 2';

COMMENT ON COLUMN dim_station.station_id IS
    'Идентификатор станции из OLTP';	

CREATE TABLE dim_bicycle (
    bicycle_key         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id          NUMBER NOT NULL,

    inventory_number    VARCHAR2(50 CHAR) NOT NULL,

    manufacturer        VARCHAR2(100 CHAR) NOT NULL,
    model_name          VARCHAR2(100 CHAR) NOT NULL,
    bicycle_type        VARCHAR2(30 CHAR) NOT NULL,

    hour_rate           NUMBER(10, 2),

    purchase_date       DATE,
    last_service_date   DATE,

    valid_from          TIMESTAMP NOT NULL,
    valid_to            TIMESTAMP,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL,

    source_updated_at   TIMESTAMP,
    load_dttm           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dim_bicycle
        PRIMARY KEY (bicycle_key),

    CONSTRAINT chk_dim_bicycle_current
        CHECK (is_current IN ('Y', 'N')),

    CONSTRAINT chk_dim_bicycle_rate
        CHECK (
            hour_rate IS NULL
            OR hour_rate >= 0
        ),

    CONSTRAINT chk_dim_bicycle_period
        CHECK (
            valid_to IS NULL
            OR valid_to > valid_from
        )
);

COMMENT ON TABLE dim_bicycle IS
    'Измерение велосипедов с денормализованными атрибутами модели';

COMMENT ON COLUMN dim_bicycle.bicycle_id IS
    'Идентификатор велосипеда из OLTP';

COMMENT ON COLUMN dim_bicycle.bicycle_key IS
    'Суррогатный ключ версии велосипеда';

CREATE TABLE fact_rentals (
    rental_fact_key       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rental_id             NUMBER NOT NULL,
    booking_id            NUMBER,

    client_key            NUMBER NOT NULL,
    bicycle_key           NUMBER NOT NULL,

    start_station_key     NUMBER NOT NULL,
    end_station_key       NUMBER,

    start_date_key        NUMBER(8) NOT NULL,
    planned_end_date_key  NUMBER(8) NOT NULL,
    actual_end_date_key   NUMBER(8),

    actual_start_at       TIMESTAMP NOT NULL,
    planned_end_at        TIMESTAMP NOT NULL,
    actual_end_at         TIMESTAMP,

    rental_status         VARCHAR2(20 CHAR) NOT NULL,

    duration_minutes      NUMBER,
    planned_minutes       NUMBER,
    overdue_minutes       NUMBER DEFAULT 0 NOT NULL,

    base_amount           NUMBER(10, 2) DEFAULT 0 NOT NULL,
    extension_amount      NUMBER(10, 2) DEFAULT 0 NOT NULL,
    penalty_amount        NUMBER(10, 2) DEFAULT 0 NOT NULL,
    total_amount          NUMBER(10, 2) DEFAULT 0 NOT NULL,

    rental_count          NUMBER(1) DEFAULT 1 NOT NULL,
    is_completed          CHAR(1) DEFAULT 'N' NOT NULL,
    is_overdue            CHAR(1) DEFAULT 'N' NOT NULL,

    source_updated_at     TIMESTAMP,
    load_dttm             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_fact_rentals
        PRIMARY KEY (rental_fact_key),

    CONSTRAINT uq_fact_rentals
        UNIQUE (rental_id),

    CONSTRAINT fk_fact_rentals_client
        FOREIGN KEY (client_key)
        REFERENCES dim_client(client_key),

    CONSTRAINT fk_fact_rentals_bicycle
        FOREIGN KEY (bicycle_key)
        REFERENCES dim_bicycle(bicycle_key),

    CONSTRAINT fk_fact_rentals_start_station
        FOREIGN KEY (start_station_key)
        REFERENCES dim_station(station_key),

    CONSTRAINT fk_fact_rentals_end_station
        FOREIGN KEY (end_station_key)
        REFERENCES dim_station(station_key),

    CONSTRAINT fk_fact_rentals_start_date
        FOREIGN KEY (start_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_rentals_planned_end_date
        FOREIGN KEY (planned_end_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_rentals_actual_end_date
        FOREIGN KEY (actual_end_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT chk_fact_rentals_completed
        CHECK (is_completed IN ('Y', 'N')),

    CONSTRAINT chk_fact_rentals_overdue
        CHECK (is_overdue IN ('Y', 'N')),

    CONSTRAINT chk_fact_rentals_count
        CHECK (rental_count = 1),

    CONSTRAINT chk_fact_rentals_duration
        CHECK (
            duration_minutes IS NULL
            OR duration_minutes >= 0
        ),

    CONSTRAINT chk_fact_rentals_planned_minutes
        CHECK (
            planned_minutes IS NULL
            OR planned_minutes >= 0
        ),

    CONSTRAINT chk_fact_rentals_overdue_minutes
        CHECK (overdue_minutes >= 0),

    CONSTRAINT chk_fact_rentals_amounts
        CHECK (
            base_amount >= 0
            AND extension_amount >= 0
            AND penalty_amount >= 0
            AND total_amount >= 0
        )
);

COMMENT ON TABLE fact_rentals IS
    'Факт аренд. Гранулярность: одна строка на одну аренду';

CREATE TABLE fact_payments (
    payment_fact_key    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    payment_id          NUMBER NOT NULL,

    client_key          NUMBER NOT NULL,
    bicycle_key         NUMBER,

    payment_date_key    NUMBER(8) NOT NULL,

    rental_id           NUMBER,
    booking_id          NUMBER,

    payment_type        VARCHAR2(20 CHAR) NOT NULL,
    payment_status      VARCHAR2(20 CHAR) NOT NULL,
    payment_method      VARCHAR2(30 CHAR),
    currency_code       VARCHAR2(3 CHAR) NOT NULL,

    amount              NUMBER(10, 2) NOT NULL,
    signed_amount       NUMBER(10, 2) NOT NULL,

    payment_count       NUMBER(1) DEFAULT 1 NOT NULL,
    is_success          CHAR(1) DEFAULT 'N' NOT NULL,
    is_refund           CHAR(1) DEFAULT 'N' NOT NULL,

    payment_created_at  TIMESTAMP NOT NULL,
    payment_paid_at     TIMESTAMP,

    source_updated_at   TIMESTAMP,
    load_dttm           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_fact_payments
        PRIMARY KEY (payment_fact_key),

    CONSTRAINT uq_fact_payments
        UNIQUE (payment_id),

    CONSTRAINT fk_fact_payments_client
        FOREIGN KEY (client_key)
        REFERENCES dim_client(client_key),

    CONSTRAINT fk_fact_payments_bicycle
        FOREIGN KEY (bicycle_key)
        REFERENCES dim_bicycle(bicycle_key),

    CONSTRAINT fk_fact_payments_date
        FOREIGN KEY (payment_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT chk_fact_payments_success
        CHECK (is_success IN ('Y', 'N')),

    CONSTRAINT chk_fact_payments_refund
        CHECK (is_refund IN ('Y', 'N')),

    CONSTRAINT chk_fact_payments_count
        CHECK (payment_count = 1),

    CONSTRAINT chk_fact_payments_amount
        CHECK (amount > 0)
);

COMMENT ON TABLE fact_payments IS
    'Факт платежей. Гранулярность: одна строка на один платёж';

COMMENT ON COLUMN fact_payments.signed_amount IS
    'Положительное значение для оплаты, отрицательное для возврата';

CREATE TABLE fact_repairs (
    repair_fact_key      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    repair_id            NUMBER NOT NULL,

    bicycle_key          NUMBER NOT NULL,

    opened_date_key      NUMBER(8) NOT NULL,
    started_date_key     NUMBER(8),
    completed_date_key   NUMBER(8),

    opened_at            TIMESTAMP NOT NULL,
    started_at           TIMESTAMP,
    completed_at         TIMESTAMP,

    repair_status        VARCHAR2(20 CHAR) NOT NULL,

    problem_description  VARCHAR2(1000 CHAR),
    repair_result        VARCHAR2(1000 CHAR),

    duration_hours       NUMBER,
    repair_cost          NUMBER(10, 2) DEFAULT 0 NOT NULL,

    repair_count         NUMBER(1) DEFAULT 1 NOT NULL,
    is_completed         CHAR(1) DEFAULT 'N' NOT NULL,

    source_updated_at    TIMESTAMP,
    load_dttm            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_fact_repairs
        PRIMARY KEY (repair_fact_key),

    CONSTRAINT uq_fact_repairs
        UNIQUE (repair_id),

    CONSTRAINT fk_fact_repairs_bicycle
        FOREIGN KEY (bicycle_key)
        REFERENCES dim_bicycle(bicycle_key),

    CONSTRAINT fk_fact_repairs_opened_date
        FOREIGN KEY (opened_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_repairs_started_date
        FOREIGN KEY (started_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_repairs_completed_date
        FOREIGN KEY (completed_date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT chk_fact_repairs_completed
        CHECK (is_completed IN ('Y', 'N')),

    CONSTRAINT chk_fact_repairs_count
        CHECK (repair_count = 1),

    CONSTRAINT chk_fact_repairs_duration
        CHECK (
            duration_hours IS NULL
            OR duration_hours >= 0
        ),

    CONSTRAINT chk_fact_repairs_cost
        CHECK (repair_cost >= 0)
);

COMMENT ON TABLE fact_repairs IS
    'Факт ремонтов. Гранулярность: одна строка на одну заявку';

CREATE TABLE etl_log (
    etl_log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,

    process_name     VARCHAR2(100 CHAR) NOT NULL,
    start_dttm       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    end_dttm         TIMESTAMP,

    status           VARCHAR2(20 CHAR) NOT NULL,

    rows_inserted    NUMBER DEFAULT 0 NOT NULL,
    rows_updated     NUMBER DEFAULT 0 NOT NULL,
    rows_rejected    NUMBER DEFAULT 0 NOT NULL,

    error_code       NUMBER,
    error_message    VARCHAR2(2000 CHAR),

    CONSTRAINT pk_etl_log
        PRIMARY KEY (etl_log_id),

    CONSTRAINT chk_etl_log_status
        CHECK (
            status IN (
                'RUNNING',
                'SUCCESS',
                'FAILED'
            )
        ),

    CONSTRAINT chk_etl_log_rows
        CHECK (
            rows_inserted >= 0
            AND rows_updated >= 0
            AND rows_rejected >= 0
        ),

    CONSTRAINT chk_etl_log_period
        CHECK (
            end_dttm IS NULL
            OR end_dttm >= start_dttm
        )
);

COMMENT ON TABLE etl_log IS
    'Журнал выполнения ETL-процессов';
	
CREATE TABLE etl_watermark (
    process_name       VARCHAR2(100 CHAR) NOT NULL,
    last_success_dttm  TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_etl_watermark
        PRIMARY KEY (process_name)
);

COMMENT ON TABLE etl_watermark IS
    'Контрольные отметки последней успешной загрузки';	
